# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'

target 'movieaholic' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!
  
  #Implementação de Biblioteca para requisições Http
  pod 'Alamofire', '~> 4.5.0'
  #Implementação para modelagem de classe em JSON
  pod 'AlamofireObjectMapper', :git =>'https://github.com/tristanhimmelman/AlamofireObjectMapper.git', :branch => 'swift-4'
  
  # Pods for movieaholic

  target 'movieaholicTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'movieaholicUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
